#!/usr/bin/env python3
"""Export the canonical Rust prize and waveform tables for the static web app."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    source = (ROOT / "crates/dgnative/src/protocol/v3/builtin.rs").read_text()
    waves = []
    for body in re.findall(r"pub const \w+: Builtin = Builtin \{(.*?)\n\};", source, re.S):
        wave = {key: re.search(rf'{key}: "([^"]+)"', body)[1] for key in ("name", "label")}
        wave["official"] = "official: true" in body
        wave["frames"] = [list(map(int, pair)) for pair in re.findall(r"\((\d+), (\d+)\)", body)]
        waves.append(wave)
    source = (ROOT / "crates/dgnative-cli/src/gacha.rs").read_text()
    prizes = []
    for body in re.findall(r'Prize \{ label: (.*?)\}', source):
        body = "label: " + body
        prize = {key: re.search(rf'{key}:\s*"([^"]+)"', body)[1] for key in ("label", "wave", "color")}
        prize.update({key: int(re.search(rf"{key}:\s*(\d+)", body)[1]) for key in ("strength_pct", "seconds", "weight")})
        prizes.append(prize)
    assert len(waves) == 8 and len(prizes) == 13, "Review the exporter when Rust tables change shape"
    return "// Generated by scripts/export-web-data.py; edit the Rust tables instead.\n" + "\n".join(
        f"export const {name} = {json.dumps(data, indent=2)};" for name, data in [("WAVES", waves), ("PRIZES", prizes)]
    ) + "\n"


if __name__ == "__main__":
    import sys
    target = ROOT / "web/data.mjs"
    output = render()
    if "--check" in sys.argv:
        if target.read_text() != output:
            raise SystemExit("Run python3 scripts/export-web-data.py to update web/data.mjs")
    else:
        target.write_text(output)
