// Generated by scripts/export-web-data.py; edit the Rust tables instead.
export const WAVES = [
  {
    "name": "breathing",
    "label": "Breathing",
    "official": true,
    "frames": [
      [
        10,
        0
      ],
      [
        10,
        20
      ],
      [
        10,
        40
      ],
      [
        10,
        60
      ],
      [
        10,
        80
      ],
      [
        10,
        100
      ],
      [
        10,
        100
      ],
      [
        10,
        100
      ],
      [
        10,
        0
      ],
      [
        10,
        0
      ],
      [
        10,
        0
      ],
      [
        10,
        0
      ]
    ]
  },
  {
    "name": "tide",
    "label": "Tide",
    "official": true,
    "frames": [
      [
        10,
        0
      ],
      [
        11,
        16
      ],
      [
        13,
        33
      ],
      [
        14,
        50
      ],
      [
        16,
        66
      ],
      [
        18,
        83
      ],
      [
        19,
        100
      ],
      [
        21,
        92
      ],
      [
        22,
        84
      ],
      [
        24,
        76
      ],
      [
        26,
        68
      ],
      [
        26,
        0
      ],
      [
        27,
        16
      ],
      [
        29,
        33
      ],
      [
        30,
        50
      ],
      [
        32,
        66
      ],
      [
        34,
        83
      ],
      [
        35,
        100
      ],
      [
        37,
        92
      ],
      [
        38,
        84
      ],
      [
        40,
        76
      ],
      [
        42,
        68
      ],
      [
        10,
        0
      ]
    ]
  },
  {
    "name": "full",
    "label": "Full power",
    "official": false,
    "frames": [
      [
        10,
        100
      ]
    ]
  },
  {
    "name": "staccato",
    "label": "Staccato",
    "official": false,
    "frames": [
      [
        10,
        100
      ],
      [
        10,
        0
      ],
      [
        10,
        100
      ],
      [
        10,
        0
      ],
      [
        10,
        100
      ],
      [
        10,
        0
      ],
      [
        10,
        0
      ],
      [
        10,
        0
      ]
    ]
  },
  {
    "name": "pulse",
    "label": "Heartbeat",
    "official": false,
    "frames": [
      [
        12,
        95
      ],
      [
        12,
        40
      ],
      [
        12,
        95
      ],
      [
        12,
        0
      ],
      [
        12,
        0
      ],
      [
        12,
        0
      ],
      [
        12,
        0
      ],
      [
        12,
        0
      ],
      [
        12,
        0
      ],
      [
        12,
        0
      ]
    ]
  },
  {
    "name": "ramp",
    "label": "Ramp",
    "official": false,
    "frames": [
      [
        15,
        0
      ],
      [
        15,
        8
      ],
      [
        15,
        16
      ],
      [
        15,
        24
      ],
      [
        15,
        32
      ],
      [
        15,
        40
      ],
      [
        15,
        48
      ],
      [
        15,
        56
      ],
      [
        15,
        64
      ],
      [
        15,
        72
      ],
      [
        15,
        80
      ],
      [
        15,
        88
      ],
      [
        15,
        96
      ],
      [
        15,
        100
      ],
      [
        15,
        100
      ],
      [
        15,
        0
      ]
    ]
  },
  {
    "name": "steps",
    "label": "Steps",
    "official": false,
    "frames": [
      [
        20,
        20
      ],
      [
        20,
        20
      ],
      [
        20,
        45
      ],
      [
        20,
        45
      ],
      [
        20,
        70
      ],
      [
        20,
        70
      ],
      [
        20,
        100
      ],
      [
        20,
        100
      ],
      [
        20,
        0
      ],
      [
        20,
        0
      ]
    ]
  },
  {
    "name": "flutter",
    "label": "Flutter",
    "official": false,
    "frames": [
      [
        120,
        55
      ],
      [
        140,
        70
      ],
      [
        160,
        60
      ],
      [
        140,
        45
      ],
      [
        120,
        65
      ]
    ]
  }
];
export const PRIZES = [
  {
    "label": "Air",
    "wave": "breathing",
    "color": "#3f4756",
    "strength_pct": 0,
    "seconds": 3,
    "weight": 16
  },
  {
    "label": "Breeze",
    "wave": "breathing",
    "color": "#46708f",
    "strength_pct": 15,
    "seconds": 4,
    "weight": 15
  },
  {
    "label": "Caress",
    "wave": "breathing",
    "color": "#4a8fb8",
    "strength_pct": 25,
    "seconds": 6,
    "weight": 15
  },
  {
    "label": "Ripple",
    "wave": "tide",
    "color": "#4e9fa8",
    "strength_pct": 30,
    "seconds": 8,
    "weight": 12
  },
  {
    "label": "Sip",
    "wave": "breathing",
    "color": "#5aa9a0",
    "strength_pct": 40,
    "seconds": 8,
    "weight": 12
  },
  {
    "label": "Steps",
    "wave": "steps",
    "color": "#6bab7e",
    "strength_pct": 45,
    "seconds": 10,
    "weight": 10
  },
  {
    "label": "Heartbeat",
    "wave": "pulse",
    "color": "#9aac52",
    "strength_pct": 55,
    "seconds": 10,
    "weight": 9
  },
  {
    "label": "Flutter",
    "wave": "flutter",
    "color": "#c9a227",
    "strength_pct": 50,
    "seconds": 12,
    "weight": 8
  },
  {
    "label": "Surge",
    "wave": "tide",
    "color": "#d9902f",
    "strength_pct": 70,
    "seconds": 12,
    "weight": 7
  },
  {
    "label": "Combo",
    "wave": "staccato",
    "color": "#d97a34",
    "strength_pct": 65,
    "seconds": 8,
    "weight": 6
  },
  {
    "label": "Crescendo",
    "wave": "ramp",
    "color": "#cf6136",
    "strength_pct": 80,
    "seconds": 16,
    "weight": 5
  },
  {
    "label": "Long Night",
    "wave": "tide",
    "color": "#8e5bb5",
    "strength_pct": 60,
    "seconds": 30,
    "weight": 4
  },
  {
    "label": "Thunder",
    "wave": "full",
    "color": "#c8443c",
    "strength_pct": 100,
    "seconds": 5,
    "weight": 3
  }
];
